### ISSUE TITLE
line 41, priors -> prior?

### ISSUE THREAD

**Issue by infoxiao** [jmhessel/FightingWords#1]
Hey Jack,
I'm curious on line 41,

```
if type(priors) is float:
```

is it actually:

```
if type(prior) is float:
```

Otherwise it complains that priors referenced before assigned.

**Comment by jmhessel** [comment]
Hi Xiao,

Thanks for the info! Just fixed this.

Jack

**Comment by infoxiao** [comment]
cool. thanks!
