### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by kenlimmj** [jmhessel/FightingWords#2]
I took CS 6742 at Cornell with Lillian Lee and this implementation got us very far. I'm hoping to fork this and wrap it in scikit-learn compliant syntax, then release it as a package. However there's no licensing information that accompanies the repository. Is it possible for that to be added?

**Comment by jmhessel** [comment]
Sure, that's fine. Is MIT okay?

**Comment by kenlimmj** [comment]
Definitely. Thank you!

**Comment by jmhessel** [comment]
Done + done. Thanks for looking into sklearn syntax :-)
