### ISSUE TITLE
Odd output

### ISSUE THREAD

**Issue by Wigder** [jmhessel/FightingWords#3]
@jmhessel, I have been trying to use your library for a project and ran into some issues with the output I am getting. Initially, I used @kenlimmj's implementation, and after running into said issue, I tried using your implementation, but came to the same scenario. I queried @kenlimmj for help, but having obtained no reply I am seeking you for assistance.

As a simple example, I am trying to compare the 2 phrases:
*the quick brown fox jumps over the lazy pig*
*the lazy purple pig jumps over the lazier donkey*

I am setting my prior to 0.05.
My CountVectorizer is initialised with no parameters (like `CV()`), so all values are defaults.

The output I get by calling `bayes_compare_language` with these parameters is:
`[('brown', -0.11159788992602564), ('donkey', -0.11159788992602564), ('fox', -0.11159788992602564), ('lazier', -0.11159788992602564), ('purple', -0.11159788992602564), ('quick', -0.11159788992602564), ('jumps', 0.04795579532980462), ('lazy', 0.04795579532980462), ('over', 0.04795579532980462), ('pig', 0.04795579532980462), ('the', 0.22827369129510436)]`

I am struggling to grasp how this is coherent with the original paper. For example, *brown* and *purple* have the same z-scores, but since the former only shows up in the first corpus and the latter only shows up in the second corpus, I imagined that the z-score for *brown* would take the absolute value of *purple*:
`('brown', 0.11159788992602564)
('purple', -0.11159788992602564)`
But the above is not the case.

I also ran this on large political corpora and the behaviour was pretty much the same. Stop words like *the*, *to* and so forth received high positive scores, while words that only showed up once within the corpora pair received high negative scores. This behaviour is clearly not what the paper describes at all so I am confused as to whether I am doing something wrong or if I'm entirely misinterpreting the output (or the paper). Any help would be highly appreciated!

I am attaching a text file with more verbose outputs I obtained, which you could peruse if you'd like more examples.
[data.txt](https://github.com/jmhessel/FightingWords/files/2972394/data.txt)

**Comment by jmhessel** [comment]
Hi @Wigder ! Thanks for trying out this code!! I ran the example you gave with the following output:
```python
l1 = ['the quick brown fox jumps over the lazy pig']
l2 = ['the lazy purple pig jumps over the lazier donkey']
from sklearn.feature_extraction.text import CountVectorizer as CV
from fightin_words import bayes_compare_language
res = bayes_compare_language(l1, l2, prior=.05, cv=CV())
```
```
[('donkey', -0.6894227886807968), ('lazier', -0.6894227886807968), ('purple', -0.6894227886807968), ('jumps', 0.0), ('lazy', 0.0), ('over', 0.0), ('pig', 0.0), ('the', 0.0), ('brown', 0.6894227886807968), ('fox', 0.6894227886807968), ('quick', 0.6894227886807968)]
```
Which, at first glance, I think makes more sense than the output you were getting.

what version of sklearn are you using, btw? perhaps CV has changed in its default parameter settings or something?

**Comment by jmhessel** [comment]
Also --- if you want to double-check me here, it would be appreciated, but I think the equations look right (if they aren't correct, I'd love to fix them!! :) ).

Noting that the `k` subscript in the paper is essentially irrelevant here...

Eq. 16 from the paper is ideally [here](https://github.com/jmhessel/FightingWords/blob/master/fighting_words.py#L55-L57)

Eq. 20 from the paper is ideally [here](https://github.com/jmhessel/FightingWords/blob/master/fighting_words.py#L59) 

Eq. 22 from the paper is ideally [here](https://github.com/jmhessel/FightingWords/blob/master/fighting_words.py#L61)

What do you think?

**Comment by Wigder** [comment]
@jmhessel I am honestly baffled, I went back to my code to run it the exact same way you showed and this time I got the exact same output as you did, so thank you so so much for your quick feedback! This is for my final year dissertation project so I will make note to give you a shout out there.

I feel like I was being really silly and that the reason I couldn't get it to work before was that I was calling the function with strings rather than lists as arguments, and I modified your code to work with strings rather than lists - amidst my modifications I must have broken something. I am so sorry for the trouble and thank you once again for the help.

I looked through the equations you sent and I can't see anything that could be wrong! I had looked before too and I did think that your code was all correct and that I must have been doing something wrong to get the output I was getting.

Having said all of that, I still can't get @kenlimmj's implementation to work the same way yours does. I have checked everything and ran the example he provided on the landing page of his repo and I keep getting those odd z-scores in the result. I will let him know about this discussion here.

**Comment by jmhessel** [comment]
Hi @Wigder ! Great to hear --- and thanks again for considering using this code :). Good luck with your dissertation project, and definitely let me know if I can be helpful in any other way. Thanks again for checking out those equations --- good to have another pair of eyes on them.

Interestingly,  @kenlimmj 's implementation is much cleaner than this one, but the math-y part looks to be the same to me. I haven't used that one, before, so I am not 100% what the differences might be.

**Comment by Wigder** [comment]
Thank you so much for your time and disposition!

Yes I think @kenlimmj's implementation is cleaner too which is why I went for it initially. I agree that it looks to be the same as yours in terms of the maths behind it, so it should work too - I reckon that I might be calling something incorrectly just like I did when attempting to use your implementation before.

**Comment by Wigder** [comment]
Hello again! I finished the project where I used your code and decided to convert it to Python 3 and packaged it accordingly. If you're interested, you can find it under https://github.com/Wigder/fightin_words.
