### ISSUE TITLE
Is count matrix populated correctly?

### ISSUE THREAD

**Issue by lejon** [jmhessel/FightingWords#4]
Hi, 

It seems to me that there is something strange with the populating of the count matrix.
Isn't it supposed to have the counts for X[0] in count_matrix[[0,:] and X[1] in count_matrix[[1,:]? I don't think that is what happens.
This is because 'count' contains the MERGED counts of l1 + l2, i.e the counts for the vocabulary, and not the counts for X[0] first and then the counts for X[1].

Or am I missing something? :)

**Comment by jmhessel** [comment]
I think the lines you're talking about are these:

https://github.com/jmhessel/FightingWords/blob/master/fighting_words.py#L37-L48

counts_mat is a document-by-vocabulary sparse matrix, where the documents are a concatenation of the `l1` and `l2` documents. Then, to get the counts of each vocabulary item for `l1`, you take the first `len(l1)` rows of counts_mat, and sum them over the vocabulary. Similarly, to get the counts of each vocabulary item for `l2`, you take the last `len(l2)` rows of counts_mat, and sum over the vocabulary.

The result is that `count_matrix[0, :]` is a vocabulary-lengthed vector containing the counts of each vocabulary item in `l1`, and `count_matrix[1, :]` is a vocabulary-lengthed vector containing the counts of each vocabulary item in `l2`.

Does that make sense?

**Comment by lejon** [comment]
Yes! You are correct and I'm confused! I was looking at the implementation https://github.com/kenlimmj/fightin-words/blob/master/fightin-words/fightin-words.py which is derived from your code and it does not behave the same way as your code, but I didn't realize that from code review only, it looked very much the same. I have now also run your code with the same input and printouts as in the above code and the behaviour is different. I have also now verified that my R implementation and your code gives the exact same output given the same input.

Sorry for polluting your issue tracker!

**Comment by jmhessel** [comment]
No worries! Thanks for checking out this library!
